language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
script: 
  - phpunit --configuration TwitterSearchApp/test/phpunit.xml
  - phpcs --standard=psr2 ./TwitterSearchApp
  - ./vendor/bin/phpmd TwitterSearchApp/ text

# Commands to be run before your environment runs.
before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - composer self-update
  - ./composer.phar install --dev --prefer-source --no-interaction
