<?php
namespace Fch;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-08 at 00:56:43.
 *
 */
class ControllerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Fch\Controller::indexAction
     */
    public function testIndexActionHasTitle()
    {
        $this->object->indexAction();

        $this->expectOutputRegex('#<h1>Twitter Search</h1>#');

    }
}
