<?php
namespace Fch;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-07 at 00:09:38.
 */
class DateUtilsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Fch\DateUtils::elapsedTime
     */
    public function testElapsedTimeDays()
    {
        $date = new \DateTime();
        $date->sub(date_interval_create_from_date_string('2 days'));

        $this->assertEquals(
            "hace 2 día(s)",
            DateUtils::elapsedTime($date->getTimestamp())
        );
    }

    /**
     * @covers Fch\DateUtils::elapsedTime
     */
    public function testElapsedTimeHours()
    {
        $date = new \DateTime();
        $date->sub(date_interval_create_from_date_string('3 hours'));

        $this->assertEquals(
            "hace 3 hora(s)",
            DateUtils::elapsedTime($date->getTimestamp())
        );
    }


}
