<?php
namespace Fch;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-07 at 00:09:38.
 */
class DateUtilsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @covers Fch\DateUtils::elapsedTime
     */
    public function testElapsedTime()
    {
        $twoDaysAgo = mktime(0, 0, 0, date("m")  , date("d")-2, date("Y"));
        $this->assertEquals("hace 2 día(s)", DateUtils::elapsedTime($twoDaysAgo));
    }
}
