<?php
namespace Fch;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-08 at 00:30:38.
 */
class IndexViewTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var IndexView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IndexView;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testRenderShowsForm()
    {
        $actual = $this->object->render();

        $matcher = array(
            'tag' => 'form',
            'class' => 'form-search'
        );

        $this->assertTag($matcher, $actual, true);
    }

    public function testRenderTweets()
    {
        $tweets = new \Fch\Twitter\TweetCollection();

        $tweet = new \Fch\Twitter\Tweet();
        $tweet->setText('dummy tweet');
        $tweet->setTweetId(1234);

        $tweets->append($tweet);

        $this->object->setVar('tweets', $tweets);

        $actual = $this->object->render();

        $matcher = array(
            'tag' => 'div',
            'id' => 'tweet1234'
        );

        $this->assertTag($matcher, $actual, true);
    }
}
