<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-07 at 00:44:18.
 */
namespace Fch\Twitter;

use Fch\Twitter\TweetCollection;

class TweetCollectionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TweetCollection
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TweetCollection;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function testEmptyCollection()
    {
        $this->assertEquals(0, $this->object->count());
    }

    /**
     * @covers Fch\Twitter\TweetCollection::append
     */
    public function testAppend()
    {
        $expected = new \Fch\Twitter\Tweet();
        $this->assertEquals(0, $this->object->count());
        $this->object->append($expected);
        $this->assertEquals(1, $this->object->count());

        $this->object->rewind();
        $this->assertEquals($expected, $this->object->current());
    }


}
