<?php
namespace Fch\Twitter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2013-03-07 at 01:04:22.
 */
class TwitterParserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var TwitterParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new TwitterParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    function mockTwitterJson() {
        return file_get_contents(dirname(__FILE__).'/mock_twitter.json');
    }

    /**
     * @dataProvider mockTwitterJson
     * @covers Fch\Twitter\TwitterParser::parse
     */
    public function testParse($json)
    {
        $actual = $this->object->parse($json);
        $this->assertEquals(1, $actual->count());
    }
}
