<!DOCTYPE html>
<html>
<head>
    <title>Twitter Search App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span4">
            <h1>Twitter Search</h1>

            <form action="index.php" class="form-search" method="get">
                <input name="q" type="text" value="<?php echo isSet($query) ? $query : '' ?>"
                       class="input-medium search-query">
                <button type="submit" class="btn">Search</button>
            </form>
        </div>
        <div class="span8" id="tweets">
            <?php
            if (!empty($tweets)) {
                foreach ($tweets as $tweet) {
                    /* @var $tweet \Fch\Twitter\Tweet */
                    printf('<div class="alert" id="tweet%s">', $tweet->getTweetId());
                    printf('<h3>%s</h3>', $tweet->getText());
                    printf('<p>%s</p>', $tweet->getElapsedTime());
                    printf('</div>');
                }
            }
            ?>
        </div>
    </div>
</div>


</body>
</html>